# Generated by Django 4.0.5 on 2022-06-03 20:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=200)),
                ('drink_ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None)),
                ('garnishes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None)),
                ('directions', models.CharField(max_length=2000)),
                ('glass', models.CharField(max_length=200)),
                ('tools', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=200)),
            ],
        ),
    ]
