# Generated by Django 4.0.5 on 2022-06-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_alter_drinks_options_alter_ingredients_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='garnishes',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='glass',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='tools',
        ),
    ]
